name: create-pr
on: 
  push: 
    branches: ["!main"]
jobs: 
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
